<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>TSM.ico</ApplicationIcon>
		<Company />
		<Product>That Sky App</Product>
		<Authors>XeTrinityz</Authors>
		<PackageId>ThatSkyApp</PackageId>
		<PackageIcon>TSM.png</PackageIcon>
		<AssemblyName>ThatSkyApp</AssemblyName>
		<Version>$(VersionPrefix)</Version>
		<Title>That Sky App</Title>
		<Description>A simple utility to help install and manage That Sky Mod.</Description>
		<RepositoryUrl>https://github.com/XeTrinityz/ThatSkyApp</RepositoryUrl>
		<SignAssembly>False</SignAssembly>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DebugType>embedded</DebugType>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Include="TSM.ico" />
	</ItemGroup>

	<ItemGroup>
	<None Remove="Resources\Localization\LocalizationResources.xaml" />
	<None Remove="Resources\Localization\LocalizationResources.zh.xaml" />
	</ItemGroup>

	<ItemGroup>
	<Resource Include="Resources\Localization\LocalizationResources.xaml" />
	<Resource Include="Resources\Localization\LocalizationResources.zh.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="MahApps.Metro" Version="2.4.10" />
	  <PackageReference Include="MahApps.Metro.IconPacks" Version="5.1.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
	  <PackageReference Include="System.Management" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="TSM.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</Resource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="UI\Styles\" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="TSM.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>